export const countries = [
    { code: '+91', name: 'India', iso: 'IN', flag: '🇮🇳' },
    { code: '+1', name: 'USA', iso: 'US', flag: '🇺🇸' },
    { code: '+44', name: 'UK', iso: 'GB', flag: '🇬🇧' },
    { code: '+971', name: 'UAE', iso: 'AE', flag: '🇦🇪' },
    { code: '+61', name: 'Australia', iso: 'AU', flag: '🇦🇺' },
    { code: '+92', name: 'Pakistan', iso: 'PK', flag: '🇵🇰' },
    { code: '+880', name: 'Bangladesh', iso: 'BD', flag: '🇧🇩' },
    { code: '+94', name: 'Sri Lanka', iso: 'LK', flag: '🇱🇰' },
    { code: '+65', name: 'Singapore', iso: 'SG', flag: '🇸🇬' },
    { code: '+1', name: 'Canada', iso: 'CA', flag: '🇨🇦' },
    { code: '+49', name: 'Germany', iso: 'DE', flag: '🇩🇪' },
    { code: '+33', name: 'France', iso: 'FR', flag: '🇫🇷' },
    { code: '+81', name: 'Japan', iso: 'JP', flag: '🇯🇵' },
    { code: '+86', name: 'China', iso: 'CN', flag: '🇨🇳' },
    { code: '+7', name: 'Russia', iso: 'RU', flag: '🇷🇺' },
    { code: '+55', name: 'Brazil', iso: 'BR', flag: '🇧🇷' },
    { code: '+27', name: 'South Africa', iso: 'ZA', flag: '🇿🇦' },
    { code: '+39', name: 'Italy', iso: 'IT', flag: '🇮🇹' },
    { code: '+34', name: 'Spain', iso: 'ES', flag: '🇪🇸' },
    { code: '+52', name: 'Mexico', iso: 'MX', flag: '🇲🇽' },
    { code: '+82', name: 'South Korea', iso: 'KR', flag: '🇰🇷' },
    { code: '+62', name: 'Indonesia', iso: 'ID', flag: '🇮🇩' },
    { code: '+60', name: 'Malaysia', iso: 'MY', flag: '🇲🇾' },
    { code: '+66', name: 'Thailand', iso: 'TH', flag: '🇹🇭' },
    { code: '+84', name: 'Vietnam', iso: 'VN', flag: '🇻🇳' },
    { code: '+63', name: 'Philippines', iso: 'PH', flag: '🇵🇭' },
    { code: '+90', name: 'Turkey', iso: 'TR', flag: '🇹🇷' },
    { code: '+966', name: 'Saudi Arabia', iso: 'SA', flag: '🇸🇦' },
    { code: '+20', name: 'Egypt', iso: 'EG', flag: '🇪🇬' },
    { code: '+234', name: 'Nigeria', iso: 'NG', flag: '🇳🇬' },
    { code: '+254', name: 'Kenya', iso: 'KE', flag: '🇰🇪' },
    { code: '+251', name: 'Ethiopia', iso: 'ET', flag: '🇪🇹' },
    { code: '+212', name: 'Morocco', iso: 'MA', flag: '🇲🇦' },
    { code: '+213', name: 'Algeria', iso: 'DZ', flag: '🇩🇿' },
    { code: '+31', name: 'Netherlands', iso: 'NL', flag: '🇳🇱' },
    { code: '+32', name: 'Belgium', iso: 'BE', flag: '🇧🇪' },
    { code: '+41', name: 'Switzerland', iso: 'CH', flag: '🇨🇭' },
    { code: '+43', name: 'Austria', iso: 'AT', flag: '🇦🇹' },
    { code: '+46', name: 'Sweden', iso: 'SE', flag: '🇸🇪' },
    { code: '+47', name: 'Norway', iso: 'NO', flag: '🇳🇴' },
    { code: '+45', name: 'Denmark', iso: 'DK', flag: '🇩🇰' },
    { code: '+358', name: 'Finland', iso: 'FI', flag: '🇫🇮' },
    { code: '+353', name: 'Ireland', iso: 'IE', flag: '🇮🇪' },
    { code: '+30', name: 'Greece', iso: 'GR', flag: '🇬🇷' },
    { code: '+351', name: 'Portugal', iso: 'PT', flag: '🇵🇹' },
    { code: '+48', name: 'Poland', iso: 'PL', flag: '🇵🇱' },
    { code: '+420', name: 'Czech Republic', iso: 'CZ', flag: '🇨🇿' },
    { code: '+36', name: 'Hungary', iso: 'HU', flag: '🇭🇺' },
    { code: '+40', name: 'Romania', iso: 'RO', flag: '🇷🇴' },
    { code: '+380', name: 'Ukraine', iso: 'UA', flag: '🇺🇦' },
    { code: '+972', name: 'Israel', iso: 'IL', flag: '🇮🇱' },
    { code: '+98', name: 'Iran', iso: 'IR', flag: '🇮🇷' },
    { code: '+964', name: 'Iraq', iso: 'IQ', flag: '🇮🇶' },
    { code: '+963', name: 'Syria', iso: 'SY', flag: '🇸🇾' },
    { code: '+961', name: 'Lebanon', iso: 'LB', flag: '🇱🇧' },
    { code: '+962', name: 'Jordan', iso: 'JO', flag: '🇯🇴' },
    { code: '+965', name: 'Kuwait', iso: 'KW', flag: '🇰🇼' },
    { code: '+974', name: 'Qatar', iso: 'QA', flag: '🇶🇦' },
    { code: '+973', name: 'Bahrain', iso: 'BH', flag: '🇧🇭' },
    { code: '+968', name: 'Oman', iso: 'OM', flag: '🇴🇲' },
    { code: '+992', name: 'Tajikistan', iso: 'TJ', flag: '🇹🇯' },
    { code: '+993', name: 'Turkmenistan', iso: 'TM', flag: '🇹🇲' },
    { code: '+994', name: 'Azerbaijan', iso: 'AZ', flag: '🇦🇿' },
    { code: '+995', name: 'Georgia', iso: 'GE', flag: '🇬🇪' },
    { code: '+374', name: 'Armenia', iso: 'AM', flag: '🇦🇲' },
    { code: '+354', name: 'Iceland', iso: 'IS', flag: '🇮🇸' },
    { code: '+54', name: 'Argentina', iso: 'AR', flag: '🇦🇷' },
    { code: '+56', name: 'Chile', iso: 'CL', flag: '🇨🇱' },
    { code: '+57', name: 'Colombia', iso: 'CO', flag: '🇨🇴' },
    { code: '+51', name: 'Peru', iso: 'PE', flag: '🇵🇪' },
    { code: '+58', name: 'Venezuela', iso: 'VE', flag: '🇻🇪' },
    { code: '+593', name: 'Ecuador', iso: 'EC', flag: '🇪🇨' },
    { code: '+591', name: 'Bolivia', iso: 'BO', flag: '🇧🇴' },
    { code: '+595', name: 'Paraguay', iso: 'PY', flag: '🇵🇾' },
    { code: '+598', name: 'Uruguay', iso: 'UY', flag: '🇺🇾' },
    { code: '+506', name: 'Costa Rica', iso: 'CR', flag: '🇨🇷' },
    { code: '+507', name: 'Panama', iso: 'PA', flag: '🇵🇦' },
    { code: '+505', name: 'Nicaragua', iso: 'NI', flag: '🇳🇮' },
    { code: '+504', name: 'Honduras', iso: 'HN', flag: '🇭🇳' },
    { code: '+503', name: 'El Salvador', iso: 'SV', flag: '🇸🇻' },
    { code: '+502', name: 'Guatemala', iso: 'GT', flag: '🇬🇹' },
    { code: '+53', name: 'Cuba', iso: 'CU', flag: '🇨🇺' },
    { code: '+1', name: 'Jamaica', iso: 'JM', flag: '🇯🇲' },
    { code: '+1', name: 'Haiti', iso: 'HT', flag: '🇭🇹' },
    { code: '+1', name: 'Dominican Republic', iso: 'DO', flag: '🇩🇴' },
    { code: '+64', name: 'New Zealand', iso: 'NZ', flag: '🇳🇿' },
];
